version: "3.9"

services:
  kilo:
    image: wallacevff/kilo-autofree:1.0.21
    ports:
      - target: 4096
        published: 4096
        protocol: tcp
        mode: ingress
      - target: 1455
        published: 1455
        protocol: tcp
        mode: ingress
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      - kilo_net

    volumes:
      - /mnt/host/d/Dev:/workspace/Dev
      - container-var:/var
      - container-usr:/usr
      - container-etc:/etc
      - container-root:/workspace
      - container-opt:/opt
    environment:
      - SHELL=/bin/bash
      - HOME=/workspace
networks:
  kilo_net:
   external: true
volumes:
  data:
    driver: local
  container-var: 
    driver: local
  container-usr: 
    driver: local
  container-etc: 
    driver: local
  container-root:
    driver: local
  container-opt:
    driver: local